apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: nagp-assignment
  labels:
    app: k8s-assignment
data:
  # service dns, not pod ip
  DB_URL: "jdbc:mysql://mysql-service.nagp-assignment.svc.cluster.local:3306/employeedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  DB_USERNAME: "root"
  MYSQL_DATABASE: "employeedb"

